---
output:
  pdf_document: default
  word_document: default
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, cache = T, results = 'hide')
```

# RCTDE on the MERFISH Hypothalamus

### Load in RCTDE results and calculate significant genes

```{r prelude}
# Load in spatialRNA data and Reference data
library(RCTD)
library(Matrix)
library(devtools)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(dplyr)
library(ggrepel)
library(fields)
library(stringr)
source('~/Documents/MIT/Research/Rafalab/Projects/slideseq/Cell Demixing/ContentStructure/DEGLAM/analysis/helper_functions/merge_de_helper.R')
load_all()
pwd = getwd()
datadir <- paste0('../../data/moffitt','/')
resultsdir <- paste0('../../results/ResultsMerfish','/')
myRCTD = readRDS(paste0(resultsdir,'myRCTDde.rds'))
myRCTDQ <- readRDS(file.path(resultsdir,'myRCTDQ.rds'))
cell_types_present <- myRCTD@internal_vars_de$cell_types_present
cell_types <- myRCTD@internal_vars_de$cell_types
gene_fits <- myRCTD@de_results$gene_fits
```

### Cell type comparison

```{r fig-0.5, fig.height = 6, fig.width = 6, fig.align='center'}
## Compare excitatory to inhibitory
cell_type_1 <- 'Excitatory'
cell_type_2 <- 'Inhibitory'
ct_ind_1 <- 2*which(cell_types == cell_type_1)
ct_ind_2 <- 2*which(cell_types == cell_type_2)
same_genes <- intersect(get_gene_list_type_wrapper(myRCTD, cell_type_1, cell_types_present),
                        get_gene_list_type_wrapper(myRCTD, cell_type_2, cell_types_present))
gene_fits$con_mat[same_genes,] ### all converged :)
rm_syt2 <- setdiff(same_genes, 'Syt2')
m1 <- gene_fits$mean_val[same_genes,cell_type_1]
m2 <- gene_fits$mean_val[same_genes,cell_type_2]
plot(m1,m2)
cor(m1, m2)^2
cor(gene_fits$mean_val[rm_syt2,cell_type_1], gene_fits$mean_val[rm_syt2,cell_type_2])^2
```

