---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, cache = T)
```

```{r libraries}
library(RCTD)
library(Matrix)
library(ggplot2)
library(ggpubr)
library(gridExtra)
library(reshape2)
resultsdir = "../Data/Slideseq/NewCerPuck_190926_08/SeuratResults/"
load(file = file.path(resultsdir,'data.Rdata'))
```

```{r fig-1, fig.height = 4, fig.width = 4, fig.align = 'center'}
my_ind = puck@cell_labels==5
plot_df <- data.frame(colSums(puck@counts[berg_genes, my_ind]) / puck@nUMI[my_ind], colSums(puck@counts[purk_genes, my_ind]) / puck@nUMI[my_ind])
colnames(plot_df) = c('Bergmann','Purkinje')
plot_df$type = "Purkinje"
plot_df_final <- plot_df[puck@nUMI[my_ind] >= 300,]
my_ind = puck@cell_labels==2
plot_df <- data.frame(colSums(puck@counts[berg_genes, my_ind]) / puck@nUMI[my_ind], colSums(puck@counts[purk_genes, my_ind]) / puck@nUMI[my_ind])
colnames(plot_df) = c('Bergmann','Purkinje')
plot_df$type = "Bergmann"
plot_df_final <- rbind(plot_df_final, plot_df[puck@nUMI[my_ind] >= 300,])
MULT <- 500
plot_df_final$Bergmann <- MULT * plot_df_final$Bergmann
plot_df_final$Purkinje <- MULT * plot_df_final$Purkinje
my_pal = pals::coolwarm(20)
p1 <- ggplot2::ggplot(plot_df_final) + 
  ggplot2::geom_point(ggplot2::aes(x=Bergmann,y=Purkinje, color = type),alpha = 0.2,size=1) + 
  ggplot2::coord_fixed() + ggplot2::theme_classic()  +
  labs(color="Cluster Cell Type") + guides(color = guide_legend(override.aes = list(size = 3,alpha=1))) + 
  scale_color_manual(values=c(my_pal[1], my_pal[20]))+ theme(legend.position="top") + xlab('Bergmann Markers') + ylab('Purkinje Markers') + scale_x_continuous(breaks = c(0,10,20), limits = c(0,20)) + scale_y_continuous(breaks = c(0,10,20), limits = c(0,20))
ggarrange(p1)
```

```{r fig.height = 4, fig.width = 8, fig.align = 'center'}
#my_grad <- scale_colour_gradientn(colors = my_pal, labels = c("Bergmann", "",'Mixture', "",'Purkinje'), limits = c(0,1))

#p3 <- plot_puck_continuous(puck, names(all_weights_un)[puck@nUMI[names(all_weights_un)] >= 100], all_weights_un, 
#                     ylimit = c(0,1), my_pal = my_pal, size = .2)+ my_grad + theme(legend.title=element_blank()) + 
#  scale_x_continuous(breaks = c(1000,3000,5000), limits = c(900,5600)) + scale_y_continuous(breaks = c(1000,3000,5000), limits = c(1000,4900))+ geom_segment(aes(x = 1300, y = 1700, xend = 1684.6, yend = 1700), color = "black")+  theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank(), axis.title.y=element_blank(),axis.text.y=element_blank(),axis.ticks.y=element_blank())

#p4 <- plot_puck_continuous(puck, names(all_weights_un)[puck@nUMI[names(all_weights_un)] >= 100], all_weights_un, 
#                     ylimit = c(0,1), my_pal = my_pal, size = 1, xlim = c(3100,4400), ylim = c(1000,2400))  + my_grad + #theme(legend.title=element_blank())+ geom_segment(aes(x = 3900, y = 2370, xend = 4054, yend = 2370), color = "black")+ theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank(), axis.title.y=element_blank(),axis.text.y=element_blank(),axis.ticks.y=element_blank())
#ggarrange(p3, p4, nrow = 1, common.legend = T)
my_mod <- function(p) {
  p + scale_x_continuous(breaks = c(1000,3000,5000), limits = c(900,5600)) + scale_y_continuous(breaks = c(1000,3000,5000), limits = c(1000,4900))+ theme(legend.position="top") + geom_segment(aes(x = 1300, y = 1700, xend = 1684.6, yend = 1700), color = "black")+  theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank(), axis.title.y=element_blank(),axis.text.y=element_blank(),axis.ticks.y=element_blank())
}

#p5 <- plot_puck_continuous(puck, names(puck@cell_labels[puck@cell_labels == 0 | puck@cell_labels == 1]), puck@nUMI, 
#                      ylimit = c(0,1), my_pal = pals::brewer.blues(20)[2:20])+  theme(legend.title=element_blank()) + scale_x_continuous(breaks = #c(1000,3000,5000), limits = c(900,5600)) + scale_y_continuous(breaks = c(1000,3000,5000), limits = c(1000,4900))+ geom_segment(aes(x = 1300, y = 1700, xend = #1684.6, yend = 1700), color = "black")+  theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank(), #axis.title.y=element_blank(),axis.text.y=element_blank(),axis.ticks.y=element_blank())

my_pal = pals::brewer.blues(20)[2:20]
p2 <- plot_puck_continuous(puck, names(puck@cell_labels[puck@cell_labels == 0 | puck@cell_labels == 1]),  factor(puck@nUMI/puck@nUMI), ylimit = c(0,1))
p2 <- my_mod(p2) + scale_color_manual("",values=c(my_pal[19]),labels = c("Granule Clusters"))  + guides(color = guide_legend(override.aes = list(size = 3,alpha=1)))
#my_mod(p2)+ggplot2::scale_colour_gradientn(paste("Granule","Weight"), colors = my_pal, limits = c(0,1), breaks = c(0,1))

load(file = "Results/SlideseqCerebellum.RData")
cell_type = "Granule"
cur_range <- c(0,15)
MULT = 500
gran_genes <- rownames(marker_data_de[marker_data_de$cell_type == cell_type,])
p1 <- plot_puck_continuous(puck,colnames(puck@counts)[puck@nUMI >= 200],MULT*colSums(puck@counts[gran_genes,])/puck@nUMI, ylimit = cur_range)
p1 <- my_mod(p1) +ggplot2::scale_colour_gradientn(paste(cell_type,"Markers"), colors = my_pal, limits = cur_range, breaks = cur_range)
 
ggarrange(p1,p2)
```
